# Generated by Django 4.0.5 on 2022-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_addprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='pic',
            field=models.ImageField(blank=True, default='profile_picture/defult.jpg', null=True, upload_to=''),
        ),
    ]
