# Generated by Django 4.0.5 on 2022-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='location', max_length=500),
        ),
    ]
