# Generated by Django 4.0.5 on 2022-07-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_addprofile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addprofile',
            old_name='pic',
            new_name='picture',
        ),
    ]
