# Generated by Django 4.0.5 on 2022-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_pic_addprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_picture/defult.jpg', null=True, upload_to='profile_picture/'),
        ),
    ]
