# Generated by Django 4.0.5 on 2022-07-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillSet',
            new_name='Skill',
        ),
    ]
