# Generated by Django 4.0.5 on 2022-08-30 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_addprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprofile',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
