# Generated by Django 4.0.5 on 2022-07-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_skillset_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddExperience',
            new_name='Experience',
        ),
    ]
