# Generated by Django 4.0.5 on 2022-08-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_addprofile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addprofile',
            name='followers',
        ),
    ]
