# Generated by Django 4.0.5 on 2022-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_addexperience_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='location', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, default='profile_picture/defult.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
