# Generated by Django 4.0.5 on 2022-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='profile_picture/defult.jpg', null=True, upload_to='profile_picture/'),
        ),
    ]
