# Generated by Django 4.0.5 on 2022-07-11 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_writer_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 11, 8, 31, 15, 738119, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
